### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by archcorsair** [steelbrain/autocomplete-swift#3]
Hi Steel,
I get this error instantly upon installation.

![image](https://cloud.githubusercontent.com/assets/1036921/14471706/a983721a-00a4-11e6-8a71-4e36849d7571.png)

Log shows:
`/Users/nxc/.atom/packages/autocomplete-swift/lib/index.js:25 autocomplete-swift scan error Error: ENOENT: no such file or directory, scandir 'atom://config'(…)`

**Comment by steelbrain** [comment]
Can you please open the dev console and show me what you see there? Please note that this package _might_ not work for files under network mount, I haven't been able to test that

**Comment by archcorsair** [comment]
I've edited the main post to include the log.
I'm testing the environment, so I'm just opening a single file from the desktop - if this makes any difference.

**Comment by steelbrain** [comment]
Based on private discussion, it seems like the OP had not added the project folder, but had opened the file directly.

This package needs project root info to determine if a project is an xcode one. We can not determine that if we only have a file path, the solution is to add the folder as a proper project folder in Atom.

Thanks again for the bug report
